name: flup_karaoke
description: A Karaoke Request Client to be used with the FLUP Karaoke Client

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: any
  shared_preferences: ^2.2.1
  karaoke_request_api:
    hosted: https://dart.pkg.jetbrains.space/flup/p/main/flup/
    version: ^1.8.9

  material_color_utilities: any
  flutter_secure_storage: ^9.0.0
  youtube_explode_dart: ^2.0.2
  auto_route: ^7.8.4
  get_it: ^7.2.0
  uni_links: ^0.5.1
  focus_detector: ^2.0.1
  url_strategy: ^0.2.0
  url_launcher: ^6.1.7
  flutter_svg: ^2.0.7
  universal_html: ^2.0.8
  dynamic_color: ^1.6.6
  json_annotation: ^4.8.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  intl: ^0.18.0
  path_provider: ^2.1.1
  infinite_scroll_pagination: ^4.0.0
  gap: ^3.0.1
  sleek_circular_slider: ^2.0.1
  modal_bottom_sheet: 3.0.0-pre
  image_cropper: ^5.0.1
  file_picker: ^6.1.1

dev_dependencies:
  isar_generator: ^3.1.0+1
  freezed: ^2.4.1
  auto_route_generator: ^7.3.1
  build_runner: ^2.1.6
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1


flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/
    - assets/fish/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        #        italic
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic


flutter_intl:
  enabled: true
  class_name: FlupS
  main_locale: en
  arb_dir: lib/res/l10n

flutter_gen:
  output: lib/generated/
  line_length: 160